### ISSUE TITLE
Is there any way to make this work more like HLDJ? (console only, etc)

### ISSUE THREAD

**Issue by zeflap** [Silvea12/PikaDJ#2]
The use of chat feels unnecessary for my needs (basically, I'd want a drop-in HLDJ replacement but know that ain't gonna happen, especially what with this being a year-old repo)
Also, firing it up while not connected to any\* server fills the console's input with '=', is this intended?

Here's hoping for an answer~

**Comment by Silvea12** [comment]
Unfortunately this uses chat hooks and does not create a GUI, so chat is required. And you need to set up your autoexec.cfg file as the README.MD says, the = is used to execute commands.

**Comment by Silvea12** [comment]
Sorry about the delay, the project is mostly dead so I don't tend to watch over it

**Comment by zeflap** [comment]
Alright, thanks for replying anyways.

For possible others running into this later not wanting to see a "nvm i fixed it :)" response, I've found https://github.com/10se1ucgo/pyjam as a more maintained replacement.
