### ISSUE TITLE
Commands aren't found

### ISSUE THREAD

**Issue by Skincanvas** [Silvea12/PikaDJ#4]
The equal sign error appeared for me in the main menu only, ingame console was normal. However when I do finally try to play something with !pikayt it simply says command not found. Now midway through writing this I thought "oh maybe I use that in chat?" so I tried it in chat and nothing seems to happen. I am using mastercomfig performance config which does not let me use autoexec files, instead I have to use custom.cfg which I figure is the same, just mentioning in case thats a (the) problem.

Or am I just misunderstanding the purpose of this software? Is it for servers only?

**Comment by Silvea12** [comment]
The software is indeed for the user to run, not the server. Have you made sure you have installed all prerequisite software as listed in the README? Command not found sounds like your command line returning this rather than the game, unless I am misunderstanding.

Also please keep in mind this project is mostly abandoned at this point, and if I were to fix it I'd likely just rewrite it from the ground up.

-------- Original Message --------

**Comment by Skincanvas** [comment]
Yeah I have all the items listed installed, except for libav-tools unless something else installed that (im using ffmpeg). Am I supposed to use one of these keybinds? What is this "exec stdin" option? Am I supposed to use the "micspamEnable" command too? As an example, once ive enabled the options "funEnabled=true" and "ttsEnabled=true", my specific error is "Unknown command: !pikasay" when used in the ingame console. If i disable the two options and then try playing a youtube video its the same error but with !pikayt

I get only this error in console on boot about 10 times;
"sv_use_steam_voice" = "0"
 replicated
  - Deprecated - placeholder convar for handling old network streams that had an incomplete SVC_VoiceInit packet.  Use "sv_voicecodec steam"

Once ingame I get these errors in tty;
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x70c5d1
  Serial number of failed request:  1396
  Current serial number in output stream:  1396
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x3c2f22b
  Serial number of failed request:  1921
  Current serial number in output stream:  1921

**Comment by TapGhoul** [comment]
This seems to be that it's either not matching the window correctly when hitting =, or something is misconfigured in xorg.
The deprecated thing is not planned to be fixed, as this project is unmaintained. If you find a way to fix it feel free to send a PR, but as of now this project is unmaintained and has no plans to be maintained in future.
